config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :recipes, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.save

    redirect_to recipe_url(@recipe.id)
  end

  private

  def recipe_params
    recipe_params = params.require(:recipe).permit(:title, :recipe_type,
                                    :cook_time, :cuisine, :ingredients,
                                    :method, :difficulty)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1> CookBook! :) </h1>

<p> 'Bem-vindo ao maior livro de receitas online' </p>

<% @recipes.each do |recipe| %>

<h1><%= link_to recipe.title, recipe %></h1>
<ul>
  <li><%= recipe.recipe_type %></li>
  <li><%= recipe.cuisine %></li>
  <li><%= recipe.difficulty %></li>
  <li><%= recipe.cook_time %> minutos </li>
</ul>
<% end %>


<%= link_to "Enviar uma receita", new_recipe_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/new.html.erb
<%= form_for(@recipe) do |f|  %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :recipe_type, 'Tipo da Receita' %>
    <%= f.text_field :recipe_type %>
  </div>
    <div>
      <%= f.label :cuisine, 'Cozinha' %>
      <%= f.text_field :cuisine %>
    </div>
    <div>
      <%= f.label :difficulty, 'Dificuldade' %>
      <%= f.text_field :difficulty %>
    </div>
    <div>
      <%= f.label :cook_time, 'Tempo de Preparo' %>
      <%= f.text_field :cook_time %>
    </div>
    <div>
      <%= f.label :ingredients, 'Ingredientes' %>
      <%= f.text_area :ingredients %>
    </div>
    <div>
      <%= f.label :method, 'Como Preparar' %>
      <%= f.text_area :method %>
    </div>

  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<h3>Detalhes</h3>
<p>
  Tipo de Receita: <%= @recipe.recipe_type %>
  Cozinha: <%= @recipe.cuisine %>
  Dificuldade <%= @recipe.difficulty %>
  Tempo de preparo <%= @recipe.cook_time %> minutos
</p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %> </p>
<h3>Como Preparar</h3>
<p><%= @recipe.method %> </p>

<h3><%= link_to "Voltar", root_path %></h3>